### PR TITLE
Added VersionSQL to List of Add-Ins

### PR DESCRIPTION
**Pull request by MikeTV**

### CODE REVIEW

**Comment by ktaranov** [comment]
Wow, @MikeTV great thanks for your pull request, on holidays I will test this addin.

**Comment by MikeTV** [comment]
You're welcome, @ktaranov !  Very interested to hear your opinion.

Any chance you could update the sqlservercentral article with this and other recent changes?  Thanks!

**Comment by ktaranov** [comment]
Yes, of course I will update tomorrow  article on sqlservercentral, but it take some time due to it will be approved and republished on site (in average according my experience its 15-20 days).

Also could you compare your product with main competitors:
- [Red Gate Source Control] (https://github.com/ktaranov/sqlserver-kit/blob/master/SSMS/SSMS_Addins.md#red-gate-control)
-  [Apex Source Control] (https://github.com/ktaranov/sqlserver-kit/blob/master/SSMS/SSMS_Addins.md#apexsql-source-control)
 - [DbForge Source Control](https://github.com/ktaranov/sqlserver-kit/blob/master/SSMS/SSMS_Addins.md#dbforge-source-control)
?

Do you have any killer features?

**Comment by MikeTV** [comment]
Thanks!

VersionSQL's killer features are "simple and lightweight".  Since the biggest hurdle to a version-controlled database is actually getting your team to commit their changes, any unnecessary complexity will slow down or disrupt the process.  Unlike the competition, VersionSQL sticks to the minimum and gets out of the way as quickly as possible.

VersionSQL also offers a free version that can be used to version control SQL Server Express instances with no other limitations.  This is useful for small sites, hobby users, or as a never-ending trial.  For everything else, the Pro version is priced extremely competitively.

**Comment by ktaranov** [comment]
Very good  product, @MikeTV. Update SQLServerCentral.com article (it will be republished during next month) and on this week I will update site.

Once again - thanks for pull request.

If I find some bugs how can I message you? Via GIT? Or you have special support email?

**Comment by MikeTV** [comment]
Thanks @ktaranov !  Please email me at michael@versionsql.com.  I'd like to hear what you think of the software.  Likes, dislikes, bugs, ideas, etc.

**Pull request merged**
